In [ ]:
import pickle
with open("../../alt_erc.txt", "rb") as f:
    alt_erc = pickle.load(f)

In [13]:
with open("../../../metalens_optimization-main-2/scripts/nrm_erc.txt", "rb") as f:
    nrm_erc = pickle.load(f)

In [24]:
import tensorflow as tf
print(alt_erc)
tf.linalg.inv(alt_erc)

tf.Tensor(
[[[[[[ 0.5+0.j  0. +0.j  0. +0.j ...  0. +0.j  0. +0.j  0. +0.j]
     [ 0. +0.j  0.5+0.j  0. +0.j ...  0. +0.j  0. +0.j  0. +0.j]
     [ 0. +0.j  0. +0.j  0.5+0.j ...  0. +0.j  0. +0.j  0. +0.j]
     ...
     [ 0. +0.j  0. +0.j  0. +0.j ...  0.5+0.j  0. +0.j  0. +0.j]
     [ 0. +0.j  0. +0.j  0. +0.j ...  0. +0.j  0.5+0.j  0. +0.j]
     [ 0. +0.j  0. +0.j  0. +0.j ...  0. +0.j  0. +0.j  0.5+0.j]]

    [[ 0.5+0.j  0. +0.j  0. +0.j ...  0. +0.j  0. +0.j  0. +0.j]
     [ 0. +0.j  0.5+0.j  0. +0.j ...  0. +0.j  0. +0.j  0. +0.j]
     [ 0. +0.j  0. +0.j  0.5+0.j ...  0. +0.j  0. +0.j  0. +0.j]
     ...
     [ 0. +0.j  0. +0.j  0. +0.j ...  0.5+0.j  0. +0.j  0. +0.j]
     [ 0. +0.j  0. +0.j  0. +0.j ...  0. +0.j  0.5+0.j  0. +0.j]
     [ 0. +0.j  0. +0.j  0. +0.j ...  0. +0.j  0. +0.j  0.5+0.j]]

    [[ 0.5+0.j  0. +0.j  0. +0.j ...  0. +0.j  0. +0.j  0. +0.j]
     [ 0. +0.j  0.5+0.j  0. +0.j ...  0. +0.j  0. +0.j  0. +0.j]
     [ 0. +0.j  0. +0.j  0.5+0.j ...  0. +0.j  0. +0.j  0

<tf.Tensor: shape=(1, 180, 180, 6, 9, 9), dtype=complex64, numpy=
array([[[[[[2.        +0.j, 0.        +0.j, 0.        +0.j, ...,
            0.        +0.j, 0.        +0.j, 0.        +0.j],
           [0.        +0.j, 2.        +0.j, 0.        +0.j, ...,
            0.        +0.j, 0.        +0.j, 0.        +0.j],
           [0.        +0.j, 0.        +0.j, 2.        +0.j, ...,
            0.        +0.j, 0.        +0.j, 0.        +0.j],
           ...,
           [0.        +0.j, 0.        +0.j, 0.        +0.j, ...,
            2.        +0.j, 0.        +0.j, 0.        +0.j],
           [0.        +0.j, 0.        +0.j, 0.        +0.j, ...,
            0.        +0.j, 2.        +0.j, 0.        +0.j],
           [0.        +0.j, 0.        +0.j, 0.        +0.j, ...,
            0.        +0.j, 0.        +0.j, 2.        +0.j]],

          [[2.        +0.j, 0.        +0.j, 0.        +0.j, ...,
            0.        +0.j, 0.        +0.j, 0.        +0.j],
           [0.        +0.j, 2.    